#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDrive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rotorWheel,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           shooter,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rotorTwist,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           turret, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*   _____             __  __ _                             _____  ___  __ ___
  / ____|           / _|/ _(_)                             | ____|/ _ \/_ |__ \
 | |  __ _ __ _   _| |_| |_ _ _ __   __ _  ___  __ _ _ __  | |__ | | | || |  ) |
 | | |_ | '__| | | |  _|  _| | '_ \ / _` |/ _ \/ _` | '__| |___ \| | | || | / /
 | |__| | |  | |_| | | | | | | | | | (_| |  __/ (_| | |     ___) | |_| || |/ /_
  \_____|_|   \__, |_| |_| |_|_| |_|\__, |\___|\__,_|_|    |____/ \___/ |_|____|
               __/ |                 __/ |
              |___/                 |___/
*/


#include "JoystickDriver.c"

// **** CONFIG ****
int threshold = 10;     // Drive input minimum value

// Twist speeds
int twistFast = 127;
int twistSlow = 64;
int twistOff = 0;

// Wheel speeds
int wheelFast = 50;
int wheelSlow = 25;
int wheelOff = 0;

// Shooter speeds
int shooterFast = 0;
int shooterMed = -35;
int shooterSlow = -55;
int shooterOff = -127;

// TurretPositions
int turretLeft = 0;
int turretRight = 0;
int turretStraight = 0;

void initializeRobot()
{

	return;
}

task main()
{

	while(true) //Loop Forever
	
		
		getJoystickSettings(joystick);
        
        // Get drive inputs                      
		int x = -vexRT[Ch1];
		int y = -vexRT[Ch3];


        // and threshold them. 
		if(abs(y) < threshold) {
			y = 0;
		}
		if(abs(x) < threshold) {
			x = 0;
		}

        // Split arcade drive - left Y axis is throttle, right X axis is turning. 
        motor[leftDrive] = ((y) + (x));
        motor[rightDrive] = ((y) - (x));

        // Dye Rotor control 
 		if(vexRT[Btn5D] == 1)
		{
            motor[rotorWheel] = wheelFast;
            motor[rotorTwist] = twistFast;
		}
		else
		{
		   motor[rotorWheel] = wheelOff;
		   motor[rotorTwist] = twistOff;
	    }
	 
        // Shooter control
        if(vexRT[Btn6U] == 1)
        {
            motor[shooter] = shooterSlow;
        }
        else
        {
            motor[shooter] = shooterOff;
        }

        // Turret control
        if(vexRT[Btn7L] == 1)
        {
            motor[turret] = turretLeft;
        }
        else if(vexRT[Btn7R] == 1)
        {
            motor[turret] = turretRight;
        }
        else
        {
            motor[turret] = turretStraight;
        }

	    //IMPORTANT UNPLUG TOP FLYWHEEL BEFORE UPLOADING CODE IT WILL START ON ITS OWN!!!!

 }
}
